import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { getDashboardStats, listMyTransactions } from "@/lib/transactions.functions";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ArrowUpRight, ArrowDownLeft, ChevronRight, Wallet, Activity, CalendarDays, Plus, Clock, TrendingUp } from "lucide-react";
import globe from "@/assets/dashboard-globe.jpg";

export const Route = createFileRoute("/_authenticated/dashboard/")({
  head: () => ({ meta: [
    { title: "Visão geral · Redox Pay" },
    { name: "description", content: "Acompanhe o seu saldo, vendas e pagamentos M-Pesa e e-Mola na Redox Pay." },
    { property: "og:title", content: "Visão geral · Redox Pay" },
    { property: "og:description", content: "Saldo, vendas e desempenho dos seus pagamentos na Redox Pay." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: Overview,
});
const money = (n: number, decimals = 0) => new Intl.NumberFormat("pt-MZ", { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(n);
const percent = (n: number, total: number) => total ? Math.round(n / total * 1000) / 10 : 0;
const periods = [{ label: "Hoje", days: 1 }, { label: "7 dias", days: 7 }, { label: "30 dias", days: 30 }, { label: "Tudo", days: 0 }];

function Overview() {
  const [days, setDays] = useState(30);
  const fetchStats = useServerFn(getDashboardStats);
  const fetchTx = useServerFn(listMyTransactions);
  const { data: stats, isLoading: statsLoading, isError: statsError, refetch: retryStats } = useQuery({ queryKey: ["stats"], queryFn: () => fetchStats() });
  const { data: txs = [], isLoading: txLoading, isError: txError, refetch: retryTx } = useQuery({ queryKey: ["tx"], queryFn: () => fetchTx() });
  const start = new Date(); start.setHours(0, 0, 0, 0); if (days) start.setDate(start.getDate() - days + 1);
  const selected = days ? txs.filter(t => new Date(t.created_at) >= start) : txs;
  const paid = selected.filter(t => t.status === "paid");
  const volume = paid.reduce((sum, t) => sum + Number(t.amount_mzn), 0);
  const net = paid.reduce((sum, t) => sum + Number(t.net_mzn ?? 0), 0);
  const fees = volume - net;
  const channels = [
    { name: "M-Pesa", sub: "Vodacom", method: "mpesa", logo: "/brands/mpesa.png", tone: "red", color: "var(--dash-red)" },
    { name: "e-Mola", sub: "Movitel", method: "emola", logo: "/brands/emola.png", tone: "amber", color: "var(--dash-amber)" },
    { name: "Todos os pagamentos", sub: "Redox Pay", method: "all", logo: "", tone: "cyan", color: "var(--dash-cyan)" },
  ];
  const today = new Date().toDateString();
  const todayNet = txs.filter(t => t.status === "paid" && new Date(t.created_at).toDateString() === today).reduce((sum, t) => sum + Number(t.net_mzn ?? 0), 0);
  const series = Array.from({ length: days || 30 }, (_, i) => {
    const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() - (days || 30) + i + 1);
    return { label: date.toLocaleDateString("pt-MZ", { day: "2-digit", month: "2-digit" }), value: paid.filter(t => new Date(t.created_at).toDateString() === date.toDateString()).reduce((sum, t) => sum + Number(t.net_mzn ?? 0), 0) };
  });
  const hourly = Array.from({ length: 24 }, (_, hour) => ({ label: `${String(hour).padStart(2,"0")}h`, value: paid.filter(t => new Date(t.created_at).getHours() === hour).length }));
  const weekday = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((label, day) => ({ label, value: paid.filter(t => new Date(t.created_at).getDay() === day).reduce((sum, t) => sum + Number(t.amount_mzn), 0) }));
  if (statsLoading || txLoading) return <div className="dash-overview space-y-8"><Skeleton className="h-10 w-56" /><Skeleton className="h-64 w-full" /><div className="grid gap-4 md:grid-cols-3">{[0,1,2].map(i => <Skeleton key={i} className="h-80 w-full" />)}</div></div>;
  if (statsError || txError) return <div className="dash-overview py-20 text-center"><h1 className="text-xl font-semibold">Não foi possível carregar a visão geral</h1><Button variant="outline" className="mt-5" onClick={() => { void retryStats(); void retryTx(); }}>Tentar novamente</Button></div>;
  return (
    <div className="dash-overview">
      <header className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 sm:flex sm:justify-between mb-8">
        <div className="min-w-0"><p className="text-xs text-muted-foreground mb-2">A sua atividade financeira</p><h1 className="text-2xl font-semibold">Visão geral<span className="text-primary-glow">.</span></h1><p className="text-xs text-muted-foreground mt-2 truncate">{stats?.profile?.full_name || stats?.profile?.business_name || "Bem-vindo"}</p></div>
        <Button asChild size="sm" className="dash-primary shrink-0"><Link to="/dashboard/new-transaction"><Plus className="size-4" /><span className="hidden sm:inline">Nova transação</span></Link></Button>
      </header>
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div className="dash-period flex items-center gap-1" aria-label="Período das vendas">{periods.map(p => <Button key={p.days} size="sm" variant="ghost" aria-pressed={days === p.days} onClick={() => setDays(p.days)} className={days === p.days ? "dash-period-active" : "text-muted-foreground"}>{p.label}</Button>)}</div><span className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />{new Date().toLocaleDateString("pt-MZ", { day: "2-digit", month: "long", year: "numeric" })}</span></div>
      <section className="dash-balance-grid grid gap-8 lg:grid-cols-[1.15fr_1fr] pb-8 border-b border-border">
        <div className="min-w-0"><p className="dash-label flex items-center gap-2"><Wallet className="size-3.5" />Saldo disponível</p><div className="dash-balance mt-4 flex items-baseline gap-3"><span className="text-xl text-muted-foreground shrink-0">MT</span><strong className="min-w-0 break-all font-semibold tabular-nums">{money(stats?.balance ?? 0, 2)}</strong></div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">Disponível para saque</span><Button asChild variant="ghost" size="sm" className="text-foreground"><Link to="/dashboard/withdrawals">Sacar<ArrowUpRight className="size-3.5" /></Link></Button></div><div className="dash-channel-bar mt-7 flex h-2 overflow-hidden rounded-full"><div className="dash-bar-red" style={{ width: `${percent(paid.filter(t => t.method === "mpesa").length, paid.length)}%` }} /><div className="dash-bar-amber" style={{ width: `${percent(paid.filter(t => t.method === "emola").length, paid.length)}%` }} /></div><div className="flex justify-between mt-3 text-[11px] text-muted-foreground"><span className="flex items-center gap-2"><span className="dash-dot dash-bar-red" />M-Pesa</span><span className="flex items-center gap-2"><span className="dash-dot dash-bar-amber" />e-Mola</span></div></div>
        <div className="grid grid-cols-2 gap-x-6 gap-y-7"><Metric label="Volume de vendas" value={money(volume)} suffix="MT" /><Metric label="Receita líquida" value={money(net)} suffix="MT" /><Metric label="Taxa de sucesso" value={`${percent(paid.length, selected.length)}%`} /><Metric label="Pagamentos recebidos" value={String(paid.length)} /><div className="col-span-2 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">Receita de hoje</span><span className="font-medium tabular-nums flex items-center gap-2"><TrendingUp className="size-3.5 text-success" />{money(todayNet,2)} MT</span></div></div>
      </section>
      <section className="mt-8"><SectionHeading title="Os seus pagamentos" detail={periods.find(p => p.days === days)?.label} /><div className="grid gap-4 md:grid-cols-3 mt-4">{channels.map(ch => {
        const rows = ch.method === "all" ? paid : paid.filter(t => t.method === ch.method);
        const sum = rows.reduce((s,t) => s + Number(t.amount_mzn),0);
        return <article key={ch.method} className={`dash-channel dash-channel-${ch.tone}`}><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-medium">{ch.logo ? <img src={ch.logo} alt="" className="size-5 rounded-sm" /> : <Activity className="size-4" />}{ch.name}</span><ArrowUpRight className="size-3.5 text-muted-foreground" /></div><div className="dash-globe-frame"><img src={globe} alt="" width={768} height={768} loading="lazy" className="dash-globe" /><span className="dash-globe-pin" /><span className="dash-globe-orbit" /></div><div className="text-center"><span className="dash-channel-count font-semibold tabular-nums">{rows.length}</span><span className="text-[11px] text-muted-foreground ml-1.5">pagamentos recebidos</span></div><div className="mt-5 pt-4 border-t border-border flex items-end justify-between"><div><p className="dash-label">Volume</p><p className="mt-1 text-xl font-semibold tabular-nums">{money(sum)} <span className="text-[11px] font-normal text-muted-foreground">MT</span></p></div><span className="text-xs text-muted-foreground">{ch.sub}</span></div></article>;
      })}</div></section>
      <section className="grid gap-8 lg:grid-cols-[1.7fr_1fr] mt-9 pb-8 border-b border-border"><div className="min-w-0"><SectionHeading title="Fluxo de caixa" detail={days === 0 ? "Últimos 30 dias" : periods.find(p => p.days === days)?.label} /><div className="mt-4"><p className="text-2xl font-semibold tabular-nums">{money(net,2)} <span className="text-xs font-normal text-muted-foreground">MT líquidos</span></p></div><div className="h-52 mt-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{ top: 10, right: 8, bottom: 0, left: 8 }}><defs><linearGradient id="dash-cash-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--dash-red)" stopOpacity={0.22} /><stop offset="100%" stopColor="var(--dash-red)" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5" /><XAxis dataKey="label" tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={30} /><Tooltip content={<ChartTooltip suffix="MT" />} /><Area type="monotone" dataKey="value" stroke="var(--dash-red)" strokeWidth={2} fill="url(#dash-cash-fill)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div></div><div><SectionHeading title="Distribuição" detail="Por canal" /><div className="space-y-5 mt-6">{channels.slice(0,2).map(ch => { const count=paid.filter(t => t.method === ch.method).length; return <div key={ch.method}><div className="flex items-center justify-between text-xs mb-2"><span className="flex items-center gap-2"><img src={ch.logo} alt="" className="size-5 rounded-sm" />{ch.name}</span><span className="tabular-nums text-muted-foreground">{percent(count,paid.length)}%</span></div><div className="h-1.5 rounded-full bg-muted overflow-hidden"><div className={`h-full dash-bar-${ch.tone}`} style={{ width: `${percent(count,paid.length)}%` }} /></div></div>; })}</div><div className="mt-7 pt-5 border-t border-border space-y-4"><FinancialRow label="Taxas no período" value={`${money(fees,2)} MT`} /><FinancialRow label="Pendentes" value={String(selected.filter(t => t.status === "pending").length)} /><FinancialRow label="Não concluídos" value={String(selected.filter(t => t.status === "failed").length)} /></div></div></section>
      <section className="mt-8"><div className="flex items-center justify-between gap-3"><SectionHeading title="Transações recentes" /><Button asChild variant="ghost" size="sm" className="text-muted-foreground"><Link to="/dashboard/transactions">Ver todas<ChevronRight className="size-3.5" /></Link></Button></div>{!selected.length ? <p className="py-12 text-center text-sm text-muted-foreground">Nenhuma transação neste período.</p> : <div className="overflow-x-auto mt-3"><table className="w-full text-sm whitespace-nowrap"><thead><tr className="border-b border-border text-left text-[11px] text-muted-foreground"><th className="py-3 font-normal">Cliente</th><th className="px-4 font-normal">Método</th><th className="px-4 font-normal">Data</th><th className="px-4 font-normal text-right">Valor</th><th className="font-normal text-right">Estado</th></tr></thead><tbody>{selected.slice(0,6).map(t => <tr key={t.id} className="border-b border-border/60 last:border-0"><td className="py-4"><div className="flex items-center gap-3"><span className="dash-avatar shrink-0">{t.status === "paid" ? <ArrowDownLeft className="size-4" /> : <Clock className="size-4" />}</span><div><p className="font-medium max-w-40 truncate">{t.customer_name || "Cliente"}</p><p className="text-[11px] text-muted-foreground mt-1">{t.customer_phone}</p></div></div></td><td className="px-4 text-xs text-muted-foreground">{t.method === "mpesa" ? "M-Pesa" : t.method === "emola" ? "e-Mola" : "Cartão"}</td><td className="px-4 text-xs text-muted-foreground">{new Date(t.created_at).toLocaleDateString("pt-MZ")}</td><td className="px-4 text-right tabular-nums"><p>{money(Number(t.amount_mzn),2)} MT</p>{t.status === "paid" && <p className="text-[11px] text-muted-foreground mt-1">Líquido {money(Number(t.net_mzn ?? 0),2)} MT</p>}</td><td className="text-right text-[11px]"><span className={`inline-flex items-center gap-1.5 ${t.status === "paid" ? "text-success" : t.status === "failed" ? "text-destructive" : "text-muted-foreground"}`}><span className="size-1.5 rounded-full bg-current" />{t.status === "paid" ? "Recebido" : t.status === "failed" ? "Falhou" : "Pendente"}</span></td></tr>)}</tbody></table></div>}</section>
      <section className="grid gap-8 lg:grid-cols-[1.7fr_1fr] mt-9 pb-8 border-b border-border"><div className="min-w-0"><SectionHeading title="Horário de pico de vendas" detail="Vendas por hora" /><div className="h-40 mt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={hourly}><XAxis dataKey="label" interval={5} axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize:10 }} /><Tooltip content={<ChartTooltip suffix="vendas" />} /><Bar dataKey="value" fill="var(--dash-cyan)" radius={[3,3,0,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></div><div><SectionHeading title="Por dia da semana" detail="Volume" /><div className="space-y-3 mt-5">{weekday.map(d => <div key={d.label} className="grid grid-cols-[28px_1fr_70px] gap-3 items-center text-[11px]"><span className="text-muted-foreground">{d.label}</span><div className="h-1.5 bg-muted rounded-full overflow-hidden"><div className="h-full dash-bar-cyan rounded-full" style={{ width:`${d.value / Math.max(1,...weekday.map(p=>p.value))*100}%` }} /></div><span className="text-right tabular-nums text-muted-foreground">{money(d.value)} MT</span></div>)}</div></div></section>
      <section className="mt-8"><SectionHeading title="Resumo financeiro" detail="Global" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-6 mt-5"><Metric label="Total transacionado" value={money(stats?.total_volume ?? 0)} suffix="MT" /><Metric label="Total de transações" value={String(stats?.total_tx ?? 0)} /><Metric label="Receita do período" value={money(net,2)} suffix="MT" /><Metric label="Saldo disponível" value={money(stats?.balance ?? 0,2)} suffix="MT" /></div></section>
    </div>
  );
}
function Metric({ label,value,suffix }: { label:string;value:string;suffix?:string }) { return <div className="min-w-0"><p className="dash-label">{label}</p><p className="mt-2 text-xl sm:text-2xl font-semibold tabular-nums break-all">{value} {suffix && <span className="text-[11px] font-normal text-muted-foreground">{suffix}</span>}</p></div>; }
function SectionHeading({ title,detail }: { title:string;detail?:string }) { return <div className="flex items-center gap-3 min-w-0"><h2 className="text-sm font-medium">{title}</h2>{detail && <span className="text-[10px] text-muted-foreground shrink-0">{detail}</span>}</div>; }
function FinancialRow({ label,value }: { label:string;value:string }) { return <div className="flex justify-between gap-3 text-xs"><span className="text-muted-foreground">{label}</span><span className="tabular-nums">{value}</span></div>; }
function ChartTooltip({ active,payload,label,suffix }: { active?:boolean;payload?: { value?:number }[];label?:string;suffix:string }) { if (!active || !payload?.length) return null; return <div className="rounded-md border border-border bg-popover p-3 text-xs shadow-sm"><p className="text-muted-foreground mb-1">{label}</p><p className="font-medium">{money(Number(payload[0]?.value ?? 0))} {suffix}</p></div>; }
